services:
  sample.bff.api:
    image: ${DOCKER_REGISTRY-}samplebffapi
    build:
      context: .
      dockerfile: Sample.BFF.API/Dockerfile
    depends_on:
      - grpcservice
      - kibana
      - elasticsearch  
    ports:
      - "5000:8080"
    networks:
      - app-network

  grpcservice:
    image: ${DOCKER_REGISTRY-}samplecustomergrcp
    build:
      context: .
      dockerfile: Sample.Customer.Grpc/Dockerfile
    depends_on:
      - mongo
      - redis
      - kafka
      - elasticsearch
      - kibana
    ports:
      - "5001:8080"
    networks:
      - app-network

  consumerapi:
    image: ${DOCKER_REGISTRY-}sampleconsumerapi
    build:
      context: .
      dockerfile: Sample.Consumer.API/Dockerfile
    depends_on:
      - kafka
      - mongo
      - elasticsearch
      - grpcservice
      - kibana 
    ports:
      - "5002:8080"
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
    ports:
      - "9200:9200"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - app-network    

volumes:
  mongo_data:
  
networks:
  app-network:
    driver: bridge